version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: tic_tac_toe
      MYSQL_USER: root
      MYSQL_PASSWORD: Venky9949@
      MYSQL_ROOT_PASSWORD: Venky9949@
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: tic_tac_toe_backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/tictactoe
      SPRING_DATASOURCE_USERNAME:root
      SPRING_DATASOURCE_PASSWORD: Venky9949@
